# Generated by Django 4.2.5 on 2023-12-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_module_tasks_tasknumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskNumber',
        ),
    ]
